// Code generated by "enumer -type=AppRole -json -sql -transform=snake-upper"; DO NOT EDIT.

package common

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_AppRoleName_0      = "ROLE_ANONYMOUSROLE_USERROLE_SHIPPER"
	_AppRoleLowerName_0 = "role_anonymousrole_userrole_shipper"
	_AppRoleName_1      = "ROLE_MODERATOR"
	_AppRoleLowerName_1 = "role_moderator"
	_AppRoleName_2      = "ROLE_ADMIN"
	_AppRoleLowerName_2 = "role_admin"
)

var (
	_AppRoleIndex_0 = [...]uint8{0, 14, 23, 35}
	_AppRoleIndex_1 = [...]uint8{0, 14}
	_AppRoleIndex_2 = [...]uint8{0, 10}
)

func (i AppRole) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _AppRoleName_0[_AppRoleIndex_0[i]:_AppRoleIndex_0[i+1]]
	case i == 4:
		return _AppRoleName_1
	case i == 8:
		return _AppRoleName_2
	default:
		return fmt.Sprintf("AppRole(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AppRoleNoOp() {
	var x [1]struct{}
	_ = x[RoleAnonymous-(0)]
	_ = x[RoleUser-(1)]
	_ = x[RoleShipper-(2)]
	_ = x[RoleModerator-(4)]
	_ = x[RoleAdmin-(8)]
}

var _AppRoleValues = []AppRole{RoleAnonymous, RoleUser, RoleShipper, RoleModerator, RoleAdmin}

var _AppRoleNameToValueMap = map[string]AppRole{
	_AppRoleName_0[0:14]:       RoleAnonymous,
	_AppRoleLowerName_0[0:14]:  RoleAnonymous,
	_AppRoleName_0[14:23]:      RoleUser,
	_AppRoleLowerName_0[14:23]: RoleUser,
	_AppRoleName_0[23:35]:      RoleShipper,
	_AppRoleLowerName_0[23:35]: RoleShipper,
	_AppRoleName_1[0:14]:       RoleModerator,
	_AppRoleLowerName_1[0:14]:  RoleModerator,
	_AppRoleName_2[0:10]:       RoleAdmin,
	_AppRoleLowerName_2[0:10]:  RoleAdmin,
}

var _AppRoleNames = []string{
	_AppRoleName_0[0:14],
	_AppRoleName_0[14:23],
	_AppRoleName_0[23:35],
	_AppRoleName_1[0:14],
	_AppRoleName_2[0:10],
}

// AppRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AppRoleString(s string) (AppRole, error) {
	if val, ok := _AppRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AppRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AppRole values", s)
}

// AppRoleValues returns all values of the enum
func AppRoleValues() []AppRole {
	return _AppRoleValues
}

// AppRoleStrings returns a slice of all String values of the enum
func AppRoleStrings() []string {
	strs := make([]string, len(_AppRoleNames))
	copy(strs, _AppRoleNames)
	return strs
}

// IsAAppRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AppRole) IsAAppRole() bool {
	for _, v := range _AppRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AppRole
func (i AppRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AppRole
func (i *AppRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AppRole should be a string, got %s", data)
	}

	var err error
	*i, err = AppRoleString(s)
	return err
}

func (i AppRole) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *AppRole) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of AppRole: %[1]T(%[1]v)", value)
	}

	val, err := AppRoleString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
